# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:Platform=$(buildPlatform) /p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)/AppxPackages" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:GenerateAppInstallerFile=true /p:AppInstallerUri=http://MyWebServer/Apps/ /p:AppxPackageSigningEnabled=true /p:PackageCertificateKeyFile="path\to\my\keyfile.pfx" /p:PackageCertificatePassword="$(mypassword)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(build.artifactStagingDirectory)'
#    ArtifactName: 'drop'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/AppxPackages'
    ArtifactName: 'drop'
    publishLocation: 'Container'